### ISSUE TITLE
Is it possible to use this to pre-plan a route from point A to point B and then have it run the simulation?

### ISSUE THREAD

**Issue by th2112** [crescentvenus/WALB#12]
Hello all, 
       
     I was wondering if it is possible to pre-plan a route by clicking on different way points then start the simulation? The route would then run from point A to Z at the pre determined speed?

**Comment by crescentvenus** [comment]
I did it as follows.

Generate way point list by Google Earth , and save it as a KML file.
Open KML with free SATGEN NMEA( https://www.labsat.co.uk/index.php/jp/free-gps-nmea-simulator-software ).   STAGEN NMEW is able to convert from KML to GPS NEMA file specifing max speed/G and so on.
Once you have NMEA file,  original gps-sdr-sim can handle to generate gps i/q signal.

**Comment by th2112** [comment]
I tried to use that process, but I get an error when loading or importing any kml file into the labsat software. I get a error of 

Application...
  Start Date      : 09/27/2018 08:42:54
  Name/Description: SatGenNMEA.exe
  Version Number  : 

Exception...
  Date   : 09/27/2018 08:45:55
  Address: 004B151A
  Module : SatGenNMEA.exe
  Type   : EAccessViolation
  Message: Access violation at address 004B151A in module 'SatGenNMEA.exe'. Read of address 0FC5D206.

Active Controls...
  Form Class   : TProgressForm
  Form Text    : Loading KML file
  Control Class: TProgressForm
  Control Text : Loading KML file

I have tried seveal KML files and also several windows PC's and I get the same thing. I  Did get a trial version of their paid software and it does work using that, but it is limited to 120 seconds of playback. 

I am using version 4.8 of the free software. I have opened a support ticket with labsat but from the looks of it they only offer support to their paid version. I have not heard anything back in over a week.  

Are you using the newest version off their website? Or happen to have a older version I could try?

thanks!
FYI I love your project. still playing around but it is pretty cool. I'm learning a lot!

**Comment by crescentvenus** [comment]
Version of SatGenNMEA.exe I'm using is V4.8i. It looks like same as one on the website now. It worked on Windows7 and Windows10.

**Comment by th2112** [comment]
it looks like the labsat software does not like the output of the kml file from google earth. Using google maps it works.

**Comment by th2112** [comment]
thanks
