### ISSUE TITLE
ERROR: Failed to open interactive motion file.

### ISSUE THREAD

**Issue by shinan6** [crescentvenus/WALB#5]
Hello! I've been trying to implement this project but seem to be stuck onto this point:
`root@raspberrypi:/home/pi/bin# ./walb.sh `
`mkfifo: cannot create fifo ‘/tmp/fifo’: File exists`
`/tmp/latlon.txt`
`ERROR: Failed to open interactive motion file.`
I followed the instructions step by step, but perhaps there's still something wrong and prevents me from success. The following is my `.sh`file, maybe you can point out the faults: 
`
#!/bin/sh`
`SAMPLE=2048000`
`POWER=0`
`BRDC=brdc0240.17n`
`N_SAT=16`
`FIFO=/tmp/fifo`
`INT_FILE=/tmp/latlon.txt`
`DATE=2017/01/24,23:53:01`
`mkfifo $FIFO`
`./gps-sdr-sim -s $SAMPLE -e $BRDC -i $INT_FILE -b8 -n $N_SAT -o $FIFO -T $DATE&`
`hackrf_transfer -t $FIFO -f $FREQ -s $SAMPLE  -x $POWER >/dev/nul`

What can I do to solve this? Thank you so much!

**Comment by crescentvenus** [comment]
First error should be corrected as follows.
if [  ! -e $FIFO ] ;   then
mkfifo $FIFO
fi

To fix  "ERROR: Failed to open interactive motion file.
You have to create  a file  as /tmp/LatLon.txt . The format of the file is like 12.34,123.45,100.
 To create /tmp/LatLon.txt  you can use scripts under the "webui"  directory.
