### ISSUE TITLE
Antenna?

### ISSUE THREAD

**Issue by MAVProxyUser** [crescentvenus/WALB#6]
Which Antenna are you using in the photo here: 
https://github.com/crescentvenus/WALB/blob/master/images/WALB.png

**Comment by crescentvenus** [comment]
Actually, it's a 50 ohm dummy load.

**Comment by MAVProxyUser** [comment]
would you mind sharing which specific one you are using? Link?

**Comment by crescentvenus** [comment]
I got it more than 20 years ago. I don't think it exists now.
How about like this one.
http://www.ebay.com/itm/2Pcs-SMA-2W-watt-male-plug-RF-coaxial-Termination-loads-DC-3GHz-50-Dummy-Load-/192004176593?hash=item2cb4573ad1:g:QaYAAOSwLqFV7i-W
