### ISSUE TITLE
Question about position fix

### ISSUE THREAD

**Issue by petrovvlz** [crescentvenus/WALB#9]
Hello.
When I compile original gps-sdr-sim my devices can't fix position (I use HackRF with TCXO). If I start your binary, tablets got gps-position in several seconds. May be something wrong in 8-bit signal of original gps-sdr-sim? I see in GPS-test application stronger signal generated by your binary. May be I need to remove anthenna gain code from my project?

**Comment by crescentvenus** [comment]
There are two ways to generate GPS signal.
a) Make a binary I/Q file at first using gps-sdr-sim, then transmit using hackrf_transfer.
b) Generate GPS signal in real time  using named pipe(FIFO).
Which way did you try ?

**Comment by petrovvlz** [comment]
I try both variants. But devices can not lock gps-signal even generated i/q file transmited via hackrf_transfer. They display in GPS Test app about 10 satellites but GNSS Status "No Fix" 5 minutes and more. I have no critical CPU load. When I start your gps-sdr-sim binary and transfer output data via named pipe all my devices get GPS location in seconds.

**Comment by crescentvenus** [comment]
Original gps-sdr-sim should be no problem if you follow the link. https://github.com/osqzss/gps-sdr-sim
I modified original gps-sdr-sim.c to make it possible to utilize multiple core of  Pi3 using threading and other minor performance optimization.

**Comment by petrovvlz** [comment]
Thank you for answers. If you didn't modify gps signal generating algorytm it help me to resolve my problem.
